BEGIN;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS COMMINTS;
DROP TABLE IF EXISTS POSTS_LIKES;

CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) UNIQUE NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTS (
    ID SERIAL PRIMARY KEY,
    "OWNER" INTEGER REFERENCES USERS(ID) NOT NULL,
    "TYPE" TEXT NOT NULL,
    CATEGORY TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    CONTENT TEXT,
    POST_TIME TIMESTAMP NOT NULL,
    VIEWS INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS COMMINTS (
    ID SERIAL PRIMARY KEY,
    "OWNER" INTEGER REFERENCES USERS(ID) NOT NULL,
    POST INTEGER REFERENCES POSTS(ID) NOT NULL,
    COMMINT_TIME TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTS_LIKES (
    "OWNER" INTEGER REFERENCES USERS(ID) NOT NULL,
    POST INTEGER REFERENCES POSTS(ID) NOT NULL,
    VOTE_TYPE INTEGER NOT NULL,
    PRIMARY KEY("OWNER", POST)
);

COMMIT;